import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

// seed para popular o bd inicial para demonstração e desenvolvimento.
export async function seed(knex: Knex): Promise<void> {
  const [rows] = await knex.raw('SELECT COUNT(*) as total FROM employees');
  const total = Number(rows[0].total);

  if (total > 0) {
    console.log('Seed: funcionários já existem na base. Pulando...');
    return;
  }

  await knex('employees').insert([
    {
      uuid: uuidv4(),
      name: 'Ana Paula Ferreira',
      address: 'Rua das Flores, 123',
      neighborhood: 'Centro',
      zipcode: '14010-100',
      phone: '(16) 99999-0001',
      salary: 5500.00,
      contract_date: '2022-03-15',
      role: 'Desenvolvedora Frontend',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Carlos Eduardo Lima',
      address: 'Av. Brasil, 456',
      neighborhood: 'Jardim América',
      zipcode: '14020-200',
      phone: '(16) 99999-0002',
      salary: 6200.00,
      contract_date: '2021-07-01',
      role: 'Desenvolvedor Backend',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Mariana Costa',
      address: 'Rua XV de Novembro, 789',
      neighborhood: 'Vila São José',
      zipcode: '14030-300',
      phone: '(16) 99999-0003',
      salary: 4800.00,
      contract_date: '2023-01-10',
      role: 'Designer UX',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Ricardo Alves',
      address: 'Rua Sete de Setembro, 321',
      neighborhood: 'Santa Cruz',
      zipcode: '14040-400',
      phone: '(16) 99999-0004',
      salary: 7500.00,
      contract_date: '2020-05-20',
      role: 'Tech Lead',
      status: 'Férias',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Juliana Mendes',
      address: 'Rua da Paz, 654',
      neighborhood: 'Jardim Paulista',
      zipcode: '14050-500',
      phone: '(16) 99999-0005',
      salary: 4200.00,
      contract_date: '2022-11-08',
      role: 'QA Engineer',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Fernando Santos',
      address: 'Av. Independência, 987',
      neighborhood: 'Alto da Boa Vista',
      zipcode: '14060-600',
      phone: null,
      salary: 3900.00,
      contract_date: '2023-06-15',
      role: 'Analista de Suporte',
      status: 'Inativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Beatriz Oliveira',
      address: 'Rua Tiradentes, 147',
      neighborhood: 'Centro',
      zipcode: '14010-200',
      phone: '(16) 99999-0007',
      salary: 8900.00,
      contract_date: '2019-02-01',
      role: 'Gerente de Projetos',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Lucas Pereira',
      address: 'Rua Floriano Peixoto, 258',
      neighborhood: 'Sumaré',
      zipcode: '14070-700',
      phone: '(16) 99999-0008',
      salary: 5100.00,
      contract_date: '2021-09-20',
      role: 'Desenvolvedor Fullstack',
      status: 'Afastado',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Camila Rodrigues',
      address: 'Rua Duque de Caxias, 369',
      neighborhood: 'Ipiranga',
      zipcode: '14080-800',
      phone: '(16) 99999-0009',
      salary: 4600.00,
      contract_date: '2022-08-30',
      role: 'Analista de Dados',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: uuidv4(),
      name: 'Rafael Nascimento',
      address: 'Rua Marechal Deodoro, 741',
      neighborhood: 'Nova Ribeirânia',
      zipcode: '14090-900',
      phone: '(16) 99999-0010',
      salary: 9800.00,
      contract_date: '2018-04-10',
      role: 'CTO',
      status: 'Ativo',
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  console.log('Seed: 10 funcionários inseridos com sucesso.');
}